<div class="andes-carousel-snapped__exhibitor-wrapper">
    <section aria-label="novedades principales" aria-roledescription="Carrusel" class="andes-carousel-snapped__container andes-carousel-snapped__container--full andes-carousel-snapped__container--with-controls andes-carousel-snapped__container--strict-boundaries" id=":R5u:">
        <div class="andes-carousel-snapped__header"></div>
        <div class="andes-carousel-snapped__controls-wrapper"><button class="andes-carousel-snapped__control andes-carousel-snapped__control--previous andes-carousel-snapped__control--size-large" type="button" aria-label="Anterior"><span aria-hidden="true" class="andes-carousel-snapped__control__icon-container"><svg aria-hidden="true" width="24" height="24" viewBox="0 0 24 24" fill="rgba(0, 0, 0, 0.9)">
                        <path d="M14.0656 4.9325L15.1263 5.99316L9.12254 11.9969L15.1325 18.0069L14.0719 19.0676L7.00122 11.9969L14.0656 4.9325Z" fill="rgba(0, 0, 0, 0.9)"></path>
                    </svg></span></button>
            <div class="andes-carousel-snapped">
                <div class="andes-carousel-snapped__wrapper" style="display: flex; will-change: transform; flex-direction: row; transition: transform 500ms ease 0s; transform: translate3d(-4047px, 0px, 0px);">
                    <div role="group" class="andes-carousel-snapped__slide" aria-label="7 de 7" style="width: 1349px; margin-right: 0px;" data-slider="6" data-shallow-slider="" aria-hidden="true" tabindex="-1"><a href="https://www.mercadolibre.cl/suscripciones/nivel-6#DEAL_ID=NO-DEAL&amp;S=MKT&amp;V=6&amp;T=MS&amp;L=20230828_loyalty_ashoka&amp;me.flow=-1&amp;me.bu=3&amp;me.audience=all&amp;me.content_id=MS-WEB_6_LOYALTY_AHSOKA-W36&amp;me.component_id=main_slider_web_ml_6&amp;me.logic=user_journey&amp;me.position=6&amp;me.bu_line=26&amp;audience=all&amp;bu=3&amp;bu_line=26&amp;component_id=main_slider_web_ml_6&amp;content_id=MS-WEB_6_LOYALTY_AHSOKA-W36&amp;flow=-1&amp;logic=user_journey&amp;position=6&amp;c_id=/home/exhibitors-carousel/element&amp;c_campaign=20230828_loyalty_ashoka&amp;c_element_order=7&amp;c_uid=a7b4b1ee-ee58-4923-b324-38f6d83c0e08" tabindex="-1"><img src="https://http2.mlstatic.com/D_NQ_837163-MLA71415755698_092023-OO.webp" alt="Disfruta del Nivel 6 en Mercado Libre" tabindex="-1"></a></div>
                    <div role="group" class="andes-carousel-snapped__slide" aria-label="1 de 7" style="width: 1349px; margin-right: 0px;" data-slider="0"><a href="https://www.mercadolibre.cl/ofertas/especial-hogar-electro-super23#DEAL_ID=MLC15334&amp;S=MKT&amp;V=1&amp;T=MS&amp;L=20230904_hogar_multi_categoria_parrillas&amp;me.flow=-1&amp;me.bu=3&amp;me.audience=all&amp;me.content_id=MS-WEB_1_PPS_OFERTAS_PATRIAS-W36&amp;me.component_id=main_slider_web_ml_0&amp;me.logic=user_journey&amp;me.position=0&amp;me.bu_line=26&amp;audience=all&amp;bu=3&amp;bu_line=26&amp;component_id=main_slider_web_ml_0&amp;content_id=MS-WEB_1_PPS_OFERTAS_PATRIAS-W36&amp;flow=-1&amp;logic=user_journey&amp;position=0&amp;c_id=/home/exhibitors-carousel/element&amp;c_campaign=20230904_hogar_multi_categoria_parrillas&amp;c_element_order=1&amp;c_uid=631ffd8e-df74-466c-97a5-80077f52c10b" tabindex="-1"><img src="https://http2.mlstatic.com/D_NQ_924859-MLA71545038631_092023-OO.webp" alt="Ofertas patrias en Mercado Libre"></a></div>
                    <div role="group" class="andes-carousel-snapped__slide andes-carousel-snapped__slide--previous" aria-label="2 de 7" style="width: 1349px; margin-right: 0px;" data-slider="1"><a href="https://www.mercadolibre.cl/c/vestuario-y-calzado#DEAL_ID=MLC15670&amp;S=MKT&amp;V=2&amp;T=MS&amp;L=20230904_moda_especial_jeans&amp;me.bu=3&amp;me.audience=all&amp;me.content_id=MS-WEB_2_JEANS-W36&amp;me.component_id=main_slider_web_ml_1&amp;me.logic=user_journey&amp;me.position=1&amp;me.bu_line=26&amp;me.flow=-1&amp;audience=all&amp;bu=3&amp;bu_line=26&amp;component_id=main_slider_web_ml_1&amp;content_id=MS-WEB_2_JEANS-W36&amp;flow=-1&amp;logic=user_journey&amp;position=1&amp;c_id=/home/exhibitors-carousel/element&amp;c_campaign=20230904_moda_especial_jeans&amp;c_element_order=2&amp;c_uid=8cbb6377-6a0a-4bba-9c5a-fe3c657ba1ee" tabindex="-1"><img src="https://http2.mlstatic.com/D_NQ_900282-MLA71415205010_092023-OO.webp" alt="Especial jeans en Mercado Libre"></a></div>
                    <div role="group" class="andes-carousel-snapped__slide andes-carousel-snapped__slide--active" aria-label="3 de 7" style="width: 1349px; margin-right: 0px;" data-slider="2"><a href="https://listado.mercadolibre.cl/_Deal_especial-hogar-electro-super23-cpg-especial#DEAL_ID=MLC15338&amp;S=MKT&amp;V=3&amp;T=MS&amp;L=20230904_cpg_fiestas_patrias&amp;me.component_id=main_slider_web_ml_2&amp;me.logic=user_journey&amp;me.position=2&amp;me.bu_line=26&amp;me.flow=-1&amp;me.bu=3&amp;me.audience=all&amp;me.content_id=MS-WEB_3_CPG-W36&amp;audience=all&amp;bu=3&amp;bu_line=26&amp;component_id=main_slider_web_ml_2&amp;content_id=MS-WEB_3_CPG-W36&amp;flow=-1&amp;logic=user_journey&amp;position=2&amp;c_id=/home/exhibitors-carousel/element&amp;c_campaign=20230904_cpg_fiestas_patrias&amp;c_element_order=3&amp;c_uid=8bd37f83-d64f-4f1f-857e-d1d247bf90f3"><img src="https://http2.mlstatic.com/D_NQ_939565-MLA71415205336_092023-OO.webp" alt="Ofertas patrias en Mercado Libre"></a></div>
                    <div role="group" class="andes-carousel-snapped__slide andes-carousel-snapped__slide--next" aria-label="4 de 7" style="width: 1349px; margin-right: 0px;" data-slider="3"><a href="https://listado.mercadolibre.cl/_Deal_ofertas-autopartes-sept23#DEAL_ID=MLC15834&amp;S=MKT&amp;V=4&amp;T=MS&amp;L=20230904_autopartes&amp;me.logic=user_journey&amp;me.position=3&amp;me.bu_line=26&amp;me.flow=-1&amp;me.bu=3&amp;me.audience=all&amp;me.content_id=MS-WEB_4_AUTOPARTES_ALL-W36&amp;me.component_id=main_slider_web_ml_3&amp;audience=all&amp;bu=3&amp;bu_line=26&amp;component_id=main_slider_web_ml_3&amp;content_id=MS-WEB_4_AUTOPARTES_ALL-W36&amp;flow=-1&amp;logic=user_journey&amp;position=3&amp;c_id=/home/exhibitors-carousel/element&amp;c_campaign=20230904_autopartes&amp;c_element_order=4&amp;c_uid=a9824bff-9d8e-4302-b0fd-ce30ae5047bb" tabindex="-1"><img src="https://http2.mlstatic.com/D_NQ_998606-MLA71459981505_092023-OO.webp" alt="Repuestos de autos en Mercado Libre"></a></div>
                    <div role="group" class="andes-carousel-snapped__slide" aria-label="5 de 7" style="width: 1349px; margin-right: 0px;" data-slider="4"><a href="https://www.mercadolibre.cl/c/computacion/mundo-gamer#DEAL_ID=MLC15886&amp;S=MKT&amp;V=5&amp;T=MS&amp;L=20230904_especial_gaming&amp;me.logic=user_journey&amp;me.position=4&amp;me.bu_line=26&amp;me.flow=-1&amp;me.bu=3&amp;me.audience=all&amp;me.content_id=MS-WEB_5_GAMING-W36&amp;me.component_id=main_slider_web_ml_4&amp;audience=all&amp;bu=3&amp;bu_line=26&amp;component_id=main_slider_web_ml_4&amp;content_id=MS-WEB_5_GAMING-W36&amp;flow=-1&amp;logic=user_journey&amp;position=4&amp;c_id=/home/exhibitors-carousel/element&amp;c_campaign=20230904_especial_gaming&amp;c_element_order=5&amp;c_uid=153f8071-5ee3-4094-ab1c-0692a45bec59" tabindex="-1"><img src="https://http2.mlstatic.com/D_NQ_957966-MLA71460249557_092023-OO.webp" alt="Especial Gaming en Mercado Libre"></a></div>
                    <div role="group" class="andes-carousel-snapped__slide" aria-label="6 de 7" style="width: 1349px; margin-right: 0px;" data-slider="5"><a href="https://www.mercadolibre.cl/ofertas/especial-pymes-2023#DEAL_ID=MLC15454&amp;S=MKT&amp;V=6&amp;T=MS&amp;L=20230904_pymes&amp;me.flow=-1&amp;me.bu=3&amp;me.audience=all&amp;me.content_id=MS-WEB_6_PYMES-W36&amp;me.component_id=main_slider_web_ml_5&amp;me.logic=user_journey&amp;me.position=5&amp;me.bu_line=26&amp;audience=all&amp;bu=3&amp;bu_line=26&amp;component_id=main_slider_web_ml_5&amp;content_id=MS-WEB_6_PYMES-W36&amp;flow=-1&amp;logic=user_journey&amp;position=5&amp;c_id=/home/exhibitors-carousel/element&amp;c_campaign=20230904_pymes&amp;c_element_order=6&amp;c_uid=f988090e-a91d-45a5-89f3-62a591046230" tabindex="-1"><img src="https://http2.mlstatic.com/D_NQ_867866-MLA71415206910_092023-OO.webp" alt="Especial pymes en Mercado Libre"></a></div>
                    <div role="group" class="andes-carousel-snapped__slide" aria-label="7 de 7" style="width: 1349px; margin-right: 0px;" data-slider="6"><a href="https://www.mercadolibre.cl/suscripciones/nivel-6#DEAL_ID=NO-DEAL&amp;S=MKT&amp;V=6&amp;T=MS&amp;L=20230828_loyalty_ashoka&amp;me.flow=-1&amp;me.bu=3&amp;me.audience=all&amp;me.content_id=MS-WEB_6_LOYALTY_AHSOKA-W36&amp;me.component_id=main_slider_web_ml_6&amp;me.logic=user_journey&amp;me.position=6&amp;me.bu_line=26&amp;audience=all&amp;bu=3&amp;bu_line=26&amp;component_id=main_slider_web_ml_6&amp;content_id=MS-WEB_6_LOYALTY_AHSOKA-W36&amp;flow=-1&amp;logic=user_journey&amp;position=6&amp;c_id=/home/exhibitors-carousel/element&amp;c_campaign=20230828_loyalty_ashoka&amp;c_element_order=7&amp;c_uid=a7b4b1ee-ee58-4923-b324-38f6d83c0e08" tabindex="-1"><img src="https://http2.mlstatic.com/D_NQ_837163-MLA71415755698_092023-OO.webp" alt="Disfruta del Nivel 6 en Mercado Libre"></a></div>
                    <div role="group" class="andes-carousel-snapped__slide" aria-label="1 de 7" style="width: 1349px; margin-right: 0px;" data-slider="0" data-shallow-slider="" aria-hidden="true" tabindex="-1"><a href="https://www.mercadolibre.cl/ofertas/especial-hogar-electro-super23#DEAL_ID=MLC15334&amp;S=MKT&amp;V=1&amp;T=MS&amp;L=20230904_hogar_multi_categoria_parrillas&amp;me.flow=-1&amp;me.bu=3&amp;me.audience=all&amp;me.content_id=MS-WEB_1_PPS_OFERTAS_PATRIAS-W36&amp;me.component_id=main_slider_web_ml_0&amp;me.logic=user_journey&amp;me.position=0&amp;me.bu_line=26&amp;audience=all&amp;bu=3&amp;bu_line=26&amp;component_id=main_slider_web_ml_0&amp;content_id=MS-WEB_1_PPS_OFERTAS_PATRIAS-W36&amp;flow=-1&amp;logic=user_journey&amp;position=0&amp;c_id=/home/exhibitors-carousel/element&amp;c_campaign=20230904_hogar_multi_categoria_parrillas&amp;c_element_order=1&amp;c_uid=631ffd8e-df74-466c-97a5-80077f52c10b" tabindex="-1"><img src="https://http2.mlstatic.com/D_NQ_924859-MLA71545038631_092023-OO.webp" alt="Ofertas patrias en Mercado Libre" tabindex="-1"></a></div>
                </div>
            </div><button class="andes-carousel-snapped__control andes-carousel-snapped__control--next andes-carousel-snapped__control--size-large" type="button" aria-label="Siguiente"><span aria-hidden="true" class="andes-carousel-snapped__control__icon-container"><svg aria-hidden="true" width="24" height="24" viewBox="0 0 24 24" fill="rgba(0, 0, 0, 0.9)">
                        <path d="M14.0656 4.9325L15.1263 5.99316L9.12254 11.9969L15.1325 18.0069L14.0719 19.0676L7.00122 11.9969L14.0656 4.9325Z" fill="rgba(0, 0, 0, 0.9)"></path>
                    </svg></span></button>
        </div>
        <ul class="andes-carousel-snapped__pagination andes-carousel-snapped__pagination--dark andes-carousel-snapped__pagination--position-inner" aria-hidden="true">
            <li class="andes-carousel-snapped__pagination-item"><button type="button" tabindex="-1"><span class="andes-visually-hidden">Página 1</span></button></li>
            <li class="andes-carousel-snapped__pagination-item"><button type="button" tabindex="-1"><span class="andes-visually-hidden">Página 2</span></button></li>
            <li class="andes-carousel-snapped__pagination-item andes-carousel-snapped__pagination-item--active"><button type="button" tabindex="-1"><span class="andes-visually-hidden">Página 3</span></button></li>
            <li class="andes-carousel-snapped__pagination-item"><button type="button" tabindex="-1"><span class="andes-visually-hidden">Página 4</span></button></li>
            <li class="andes-carousel-snapped__pagination-item"><button type="button" tabindex="-1"><span class="andes-visually-hidden">Página 5</span></button></li>
            <li class="andes-carousel-snapped__pagination-item"><button type="button" tabindex="-1"><span class="andes-visually-hidden">Página 6</span></button></li>
            <li class="andes-carousel-snapped__pagination-item"><button type="button" tabindex="-1"><span class="andes-visually-hidden">Página 7</span></button></li>
        </ul>
    </section>
</div>